import { TemplateConfiguration } from "./templateTypes";

export const DEFAULT_TEMPLATE_CONFIG: TemplateConfiguration = {
  title: "CERTIFICATE OF PARTICIPATION",
  subtitle: "THIS IS PROUDLY PRESENTED TO",
  descriptionText: "for active and meritorious participation in the event organized by",
  backgroundColor: "#F5F5DC", // Institutional Cream
  borderStyle: "ornate-gold",
  showSeal: true,
  sealText: "OFFICIAL VERIFIED",
  fields: [
    {
      id: "field-header-org",
      key: "ORGANIZER",
      label: "Organizer / Institution",
      type: "text",
      defaultText: "KONGU ENGINEERING COLLEGE (AUTONOMOUS)",
      x: 50,
      y: 14,
      width: 80,
      height: 6,
      fontSize: 14,
      fontFamily: "Helvetica-Bold",
      fontWeight: "bold",
      textAlign: "center",
      color: "#8D6E63", // Deep warm gold/brown
      letterSpacing: 2,
    },
    {
      id: "field-title",
      key: "TITLE",
      label: "Certificate Title",
      type: "text",
      defaultText: "CERTIFICATE OF PARTICIPATION",
      x: 50,
      y: 22,
      width: 80,
      height: 8,
      fontSize: 26,
      fontFamily: "Times-Bold",
      fontWeight: "bold",
      textAlign: "center",
      color: "#C62828", // Brand Red
      letterSpacing: 3,
    },
    {
      id: "field-subtitle",
      key: "SUBTITLE",
      label: "Subtitle",
      type: "text",
      defaultText: "THIS IS PROUDLY PRESENTED TO",
      x: 50,
      y: 31,
      width: 60,
      height: 4,
      fontSize: 11,
      fontFamily: "Helvetica",
      fontWeight: "normal",
      textAlign: "center",
      color: "#57534E",
      letterSpacing: 2,
    },
    {
      id: "field-participant-name",
      key: "PARTICIPANT_NAME",
      label: "Participant Name",
      type: "text",
      defaultText: "{{PARTICIPANT_NAME}}",
      x: 50,
      y: 41,
      width: 80,
      height: 10,
      fontSize: 28,
      fontFamily: "Times-Bold",
      fontWeight: "bold",
      textAlign: "center",
      color: "#1C1917", // Primary Dark
      letterSpacing: 1,
    },
    {
      id: "field-participant-details",
      key: "ROLL_NUMBER",
      label: "Roll Number & Dept",
      type: "text",
      defaultText: "Roll No: {{ROLL_NUMBER}}",
      x: 50,
      y: 50,
      width: 70,
      height: 5,
      fontSize: 13,
      fontFamily: "Helvetica-Bold",
      fontWeight: "bold",
      textAlign: "center",
      color: "#57534E",
    },
    {
      id: "field-description",
      key: "DESCRIPTION",
      label: "Event Body Text",
      type: "text",
      defaultText: "for successful participation in {{EVENT_NAME}} organized on {{EVENT_DATE}}",
      x: 50,
      y: 57,
      width: 76,
      height: 7,
      fontSize: 13,
      fontFamily: "Times-Roman",
      fontWeight: "normal",
      textAlign: "center",
      color: "#292524",
    },
    {
      id: "field-qr",
      key: "QR_CODE",
      label: "Verification QR Code",
      type: "qr",
      x: 12,
      y: 77,
      width: 14,
      height: 14,
      fontSize: 10,
      textAlign: "center",
      color: "#1C1917",
      qrSize: 75,
      qrMargin: 1,
    },
    {
      id: "field-cert-id",
      key: "CERTIFICATE_ID",
      label: "Certificate ID",
      type: "text",
      defaultText: "ID: {{CERTIFICATE_ID}}",
      x: 88,
      y: 86,
      width: 30,
      height: 5,
      fontSize: 10,
      fontFamily: "Courier",
      fontWeight: "bold",
      textAlign: "right",
      color: "#57534E",
      letterSpacing: 1,
    },
    {
      id: "field-sign-1",
      key: "CUSTOM_TEXT_1",
      label: "Left Signatory",
      type: "custom_text",
      defaultText: "Dr. K. S. Ravichandran\nConvenor / Coordinator",
      x: 28,
      y: 84,
      width: 25,
      height: 7,
      fontSize: 10,
      fontFamily: "Helvetica",
      fontWeight: "normal",
      textAlign: "center",
      color: "#44403C",
    },
    {
      id: "field-sign-2",
      key: "CUSTOM_TEXT_2",
      label: "Right Signatory",
      type: "custom_text",
      defaultText: "Dr. P. Balasubramanian\nPrincipal & Patron",
      x: 72,
      y: 84,
      width: 25,
      height: 7,
      fontSize: 10,
      fontFamily: "Helvetica",
      fontWeight: "normal",
      textAlign: "center",
      color: "#44403C",
    },
  ],
};
